name: Interconnect
version: '${version}'

main: de.petrichor.nekyia.interconnect.Interconnect
api-version: '26.2'
load: STARTUP

authors: [ gerryxn ]

commands:
  db:
    description: Manage local test databases.
    usage: /db reset <plugin>
    permission: interconnect.db

permissions:
  interconnect.db:
    description: Allows resetting local test databases.
    default: op
