[versions]
paper-api = "26.2.build.+"
minecraft = "26.2"
mariadb4j = "3.3.1"
mariadb-java-client = "3.5.10"

paperweight-userdev = "2.0.0-beta.23"
shadow = "9.6.1"
run-task = "3.0.2"

[libraries]
mariadb4j = { module = "ch.vorburger.mariaDB4j:mariaDB4j", version.ref = "mariadb4j" }
mariadb-java-client = { module = "org.mariadb.jdbc:mariadb-java-client", version.ref = "mariadb-java-client" }

[plugins]
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight-userdev" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-task" }
